/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frm.oce.peps.vista;

/**
 *
 * @author ariel
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_Principal = new javax.swing.JPanel();
        jL_Titulo = new javax.swing.JLabel();
        jL_Contabilidad = new javax.swing.JLabel();
        jL_Contabilidad1 = new javax.swing.JLabel();
        jL_Productos = new javax.swing.JLabel();
        jCB_Productos = new javax.swing.JComboBox<>();
        jB_Cargar = new javax.swing.JButton();
        jB_Guardar = new javax.swing.JButton();
        jB_Crear = new javax.swing.JButton();
        jB_Eliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(44, 62, 80));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jP_Principal.setBackground(new java.awt.Color(44, 62, 80));

        jL_Titulo.setBackground(new java.awt.Color(236, 240, 241));
        jL_Titulo.setFont(new java.awt.Font("Anton", 0, 36)); // NOI18N
        jL_Titulo.setForeground(new java.awt.Color(236, 240, 241));
        jL_Titulo.setText("P.E.P.S.");

        jL_Contabilidad.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        jL_Contabilidad.setForeground(new java.awt.Color(236, 240, 241));
        jL_Contabilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/UTN-FRM.png"))); // NOI18N

        jL_Contabilidad1.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        jL_Contabilidad1.setForeground(new java.awt.Color(236, 240, 241));
        jL_Contabilidad1.setText("Proyecto Contabilidad 2020");

        jL_Productos.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        jL_Productos.setForeground(new java.awt.Color(255, 255, 255));
        jL_Productos.setText("Producto");

        jB_Cargar.setText("Cargar");

        jB_Guardar.setText("Guardar");

        jB_Crear.setText("Crear");

        jB_Eliminar.setText("Eliminar");

        javax.swing.GroupLayout jP_PrincipalLayout = new javax.swing.GroupLayout(jP_Principal);
        jP_Principal.setLayout(jP_PrincipalLayout);
        jP_PrincipalLayout.setHorizontalGroup(
            jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_PrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_PrincipalLayout.createSequentialGroup()
                        .addGroup(jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_Contabilidad1)
                            .addComponent(jL_Titulo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jL_Contabilidad))
                    .addGroup(jP_PrincipalLayout.createSequentialGroup()
                        .addComponent(jL_Productos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCB_Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_Cargar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_Guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_Crear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_Eliminar)
                        .addGap(0, 35, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jP_PrincipalLayout.setVerticalGroup(
            jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_PrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Productos)
                    .addComponent(jCB_Productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Cargar)
                    .addComponent(jB_Guardar)
                    .addComponent(jB_Crear)
                    .addComponent(jB_Eliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                .addGroup(jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL_Contabilidad)
                    .addGroup(jP_PrincipalLayout.createSequentialGroup()
                        .addComponent(jL_Titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jL_Contabilidad1)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_Principal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Cargar;
    private javax.swing.JButton jB_Crear;
    private javax.swing.JButton jB_Eliminar;
    private javax.swing.JButton jB_Guardar;
    private javax.swing.JComboBox<String> jCB_Productos;
    private javax.swing.JLabel jL_Contabilidad;
    private javax.swing.JLabel jL_Contabilidad1;
    private javax.swing.JLabel jL_Productos;
    private javax.swing.JLabel jL_Titulo;
    private javax.swing.JPanel jP_Principal;
    // End of variables declaration//GEN-END:variables
}
