/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frm.oce.peps.vista;

/**
 *
 * @author ariel
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_Principal = new javax.swing.JPanel();
        jL_Titulo = new javax.swing.JLabel();
        jL_Contabilidad = new javax.swing.JLabel();
        jL_Contabilidad1 = new javax.swing.JLabel();
        jL_Productos = new javax.swing.JLabel();
        jCB_Productos = new javax.swing.JComboBox<>();
        jB_Cargar = new javax.swing.JButton();
        jB_Crear = new javax.swing.JButton();
        jP_Producto = new javax.swing.JPanel();
        jL_Stock = new javax.swing.JLabel();
        jL_Precio = new javax.swing.JLabel();
        jTF_Stock = new javax.swing.JTextField();
        jTF_Precio = new javax.swing.JTextField();
        jL_FechaActual = new javax.swing.JLabel();
        jL_VentaMes = new javax.swing.JLabel();
        jL_VentaTotal = new javax.swing.JLabel();
        jTF_VentaMes = new javax.swing.JTextField();
        jTF_VentaTotal = new javax.swing.JTextField();
        jL_Resumen = new javax.swing.JLabel();
        jCB_Fecha = new javax.swing.JComboBox<>();
        jB_CargarFecha = new javax.swing.JButton();
        jP_Registro = new javax.swing.JPanel();
        jL_NuevoRegistro = new javax.swing.JLabel();
        jTF_PrecioUR = new javax.swing.JTextField();
        jC_PrecioUR = new javax.swing.JCheckBox();
        jTF_UnidadesR = new javax.swing.JTextField();
        jL_PrecioUnitarioR = new javax.swing.JLabel();
        jL_UnidadesR = new javax.swing.JLabel();
        jB_Registrar = new javax.swing.JButton();
        jP_Salida = new javax.swing.JPanel();
        jL_UnidadesS = new javax.swing.JLabel();
        jTF_UnidadesS = new javax.swing.JTextField();
        jL_Salida = new javax.swing.JLabel();
        jL_DisponibilidadS = new javax.swing.JLabel();
        jTF_DisponibiliadS = new javax.swing.JTextField();
        jB_Salida = new javax.swing.JButton();
        jL_FechaValor = new javax.swing.JLabel();
        jL_Fecha = new javax.swing.JLabel();
        jL_NuevoProducto = new javax.swing.JLabel();
        jTF_NuevoProducto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(44, 62, 80));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);

        jP_Principal.setBackground(new java.awt.Color(44, 62, 80));

        jL_Titulo.setBackground(new java.awt.Color(236, 240, 241));
        jL_Titulo.setFont(new java.awt.Font("Anton", 0, 36)); // NOI18N
        jL_Titulo.setForeground(new java.awt.Color(236, 240, 241));
        jL_Titulo.setText("P.E.P.S.");

        jL_Contabilidad.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        jL_Contabilidad.setForeground(new java.awt.Color(236, 240, 241));
        jL_Contabilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/UTN-FRM.png"))); // NOI18N

        jL_Contabilidad1.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        jL_Contabilidad1.setForeground(new java.awt.Color(236, 240, 241));
        jL_Contabilidad1.setText("Proyecto Contabilidad 2020");

        jL_Productos.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        jL_Productos.setForeground(new java.awt.Color(255, 255, 255));
        jL_Productos.setText("Producto");

        jB_Cargar.setText("Cargar");

        jB_Crear.setText("Crear");

        jP_Producto.setBackground(new java.awt.Color(52, 73, 94));

        jL_Stock.setFont(new java.awt.Font("Teko Light", 0, 18)); // NOI18N
        jL_Stock.setForeground(new java.awt.Color(255, 255, 255));
        jL_Stock.setText("Disponibilidad");

        jL_Precio.setFont(new java.awt.Font("Teko Light", 0, 18)); // NOI18N
        jL_Precio.setForeground(new java.awt.Color(255, 255, 255));
        jL_Precio.setText("Precio");

        jTF_Stock.setEditable(false);
        jTF_Stock.setBackground(new java.awt.Color(44, 62, 80));
        jTF_Stock.setForeground(new java.awt.Color(255, 255, 255));

        jTF_Precio.setEditable(false);
        jTF_Precio.setBackground(new java.awt.Color(44, 62, 80));
        jTF_Precio.setForeground(new java.awt.Color(255, 255, 255));

        jL_FechaActual.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jL_FechaActual.setForeground(new java.awt.Color(255, 255, 255));
        jL_FechaActual.setText("Fecha");

        jL_VentaMes.setFont(new java.awt.Font("Teko Light", 0, 18)); // NOI18N
        jL_VentaMes.setForeground(new java.awt.Color(255, 255, 255));
        jL_VentaMes.setText("Venta | Mes");

        jL_VentaTotal.setFont(new java.awt.Font("Teko Light", 0, 18)); // NOI18N
        jL_VentaTotal.setForeground(new java.awt.Color(255, 255, 255));
        jL_VentaTotal.setText("Venta | Total");

        jTF_VentaMes.setEditable(false);
        jTF_VentaMes.setBackground(new java.awt.Color(44, 62, 80));
        jTF_VentaMes.setForeground(new java.awt.Color(255, 255, 255));

        jTF_VentaTotal.setEditable(false);
        jTF_VentaTotal.setBackground(new java.awt.Color(44, 62, 80));
        jTF_VentaTotal.setForeground(new java.awt.Color(255, 255, 255));

        jL_Resumen.setFont(new java.awt.Font("Work Sans", 1, 24)); // NOI18N
        jL_Resumen.setForeground(new java.awt.Color(255, 255, 255));
        jL_Resumen.setText("Resumen General");

        jCB_Fecha.setBackground(new java.awt.Color(44, 62, 80));
        jCB_Fecha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hoy" }));

        jB_CargarFecha.setText("Cargar");

        javax.swing.GroupLayout jP_ProductoLayout = new javax.swing.GroupLayout(jP_Producto);
        jP_Producto.setLayout(jP_ProductoLayout);
        jP_ProductoLayout.setHorizontalGroup(
            jP_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_ProductoLayout.createSequentialGroup()
                        .addGroup(jP_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL_VentaTotal)
                            .addComponent(jL_VentaMes)
                            .addComponent(jL_Stock)
                            .addComponent(jL_Precio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jP_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_Stock)
                            .addComponent(jTF_Precio, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTF_VentaMes)
                            .addComponent(jTF_VentaTotal)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_ProductoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jL_FechaActual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCB_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_CargarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP_ProductoLayout.createSequentialGroup()
                        .addComponent(jL_Resumen)
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jP_ProductoLayout.setVerticalGroup(
            jP_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_Resumen)
                .addGap(18, 18, 18)
                .addGroup(jP_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCB_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_CargarFecha)
                    .addComponent(jL_FechaActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jP_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Stock)
                    .addComponent(jTF_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Precio)
                    .addComponent(jTF_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_VentaMes)
                    .addComponent(jTF_VentaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_VentaTotal)
                    .addComponent(jTF_VentaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jP_Registro.setBackground(new java.awt.Color(52, 73, 94));

        jL_NuevoRegistro.setFont(new java.awt.Font("Work Sans", 1, 24)); // NOI18N
        jL_NuevoRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jL_NuevoRegistro.setText("Nuevo Registro");

        jTF_PrecioUR.setEditable(false);
        jTF_PrecioUR.setBackground(new java.awt.Color(44, 62, 80));
        jTF_PrecioUR.setForeground(new java.awt.Color(255, 255, 255));

        jC_PrecioUR.setBackground(new java.awt.Color(52, 73, 94));
        jC_PrecioUR.setFont(new java.awt.Font("Teko Light", 0, 18)); // NOI18N
        jC_PrecioUR.setForeground(new java.awt.Color(255, 255, 255));

        jTF_UnidadesR.setBackground(new java.awt.Color(44, 62, 80));
        jTF_UnidadesR.setForeground(new java.awt.Color(255, 255, 255));

        jL_PrecioUnitarioR.setFont(new java.awt.Font("Teko Light", 0, 18)); // NOI18N
        jL_PrecioUnitarioR.setForeground(new java.awt.Color(255, 255, 255));
        jL_PrecioUnitarioR.setText("Precio Unitario");

        jL_UnidadesR.setFont(new java.awt.Font("Teko Light", 0, 18)); // NOI18N
        jL_UnidadesR.setForeground(new java.awt.Color(255, 255, 255));
        jL_UnidadesR.setText("Unidades");

        jB_Registrar.setText("Registrar");

        javax.swing.GroupLayout jP_RegistroLayout = new javax.swing.GroupLayout(jP_Registro);
        jP_Registro.setLayout(jP_RegistroLayout);
        jP_RegistroLayout.setHorizontalGroup(
            jP_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_RegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_RegistroLayout.createSequentialGroup()
                        .addGroup(jP_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL_UnidadesR)
                            .addComponent(jL_PrecioUnitarioR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jP_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jP_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jB_Registrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTF_UnidadesR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jP_RegistroLayout.createSequentialGroup()
                                .addComponent(jTF_PrecioUR, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jC_PrecioUR))))
                    .addComponent(jL_NuevoRegistro))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jP_RegistroLayout.setVerticalGroup(
            jP_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_RegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_NuevoRegistro)
                .addGap(19, 19, 19)
                .addGroup(jP_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTF_PrecioUR)
                    .addComponent(jC_PrecioUR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jL_PrecioUnitarioR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jL_UnidadesR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTF_UnidadesR, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jB_Registrar)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jP_Salida.setBackground(new java.awt.Color(52, 73, 94));

        jL_UnidadesS.setFont(new java.awt.Font("Teko Light", 0, 18)); // NOI18N
        jL_UnidadesS.setForeground(new java.awt.Color(255, 255, 255));
        jL_UnidadesS.setText("Unidades");

        jTF_UnidadesS.setBackground(new java.awt.Color(44, 62, 80));
        jTF_UnidadesS.setForeground(new java.awt.Color(255, 255, 255));

        jL_Salida.setFont(new java.awt.Font("Work Sans", 1, 24)); // NOI18N
        jL_Salida.setForeground(new java.awt.Color(255, 255, 255));
        jL_Salida.setText("Salida");

        jL_DisponibilidadS.setFont(new java.awt.Font("Teko Light", 0, 18)); // NOI18N
        jL_DisponibilidadS.setForeground(new java.awt.Color(255, 255, 255));
        jL_DisponibilidadS.setText("Disponibilidad");

        jTF_DisponibiliadS.setBackground(new java.awt.Color(44, 62, 80));
        jTF_DisponibiliadS.setForeground(new java.awt.Color(255, 255, 255));

        jB_Salida.setText("Enviar Salida");

        javax.swing.GroupLayout jP_SalidaLayout = new javax.swing.GroupLayout(jP_Salida);
        jP_Salida.setLayout(jP_SalidaLayout);
        jP_SalidaLayout.setHorizontalGroup(
            jP_SalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_SalidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_SalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_SalidaLayout.createSequentialGroup()
                        .addComponent(jL_Salida)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_SalidaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jP_SalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_SalidaLayout.createSequentialGroup()
                                .addComponent(jL_UnidadesS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_UnidadesS, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_SalidaLayout.createSequentialGroup()
                                .addComponent(jL_DisponibilidadS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_DisponibiliadS, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jB_Salida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jP_SalidaLayout.setVerticalGroup(
            jP_SalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_SalidaLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jL_Salida)
                .addGap(18, 18, 18)
                .addGroup(jP_SalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_UnidadesS)
                    .addComponent(jTF_UnidadesS, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_SalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_DisponibilidadS)
                    .addComponent(jTF_DisponibiliadS, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB_Salida)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jL_FechaValor.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jL_FechaValor.setForeground(new java.awt.Color(255, 255, 255));
        jL_FechaValor.setText("15/11/2020");

        jL_Fecha.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jL_Fecha.setForeground(new java.awt.Color(255, 255, 255));
        jL_Fecha.setText("Fecha:");

        jL_NuevoProducto.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        jL_NuevoProducto.setForeground(new java.awt.Color(255, 255, 255));
        jL_NuevoProducto.setText("Nombre");

        javax.swing.GroupLayout jP_PrincipalLayout = new javax.swing.GroupLayout(jP_Principal);
        jP_Principal.setLayout(jP_PrincipalLayout);
        jP_PrincipalLayout.setHorizontalGroup(
            jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_PrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jP_PrincipalLayout.createSequentialGroup()
                        .addComponent(jP_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jP_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP_PrincipalLayout.createSequentialGroup()
                        .addGroup(jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_Titulo)
                            .addComponent(jL_Contabilidad1))
                        .addGap(116, 116, 116)
                        .addGroup(jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jP_PrincipalLayout.createSequentialGroup()
                                .addComponent(jL_Fecha)
                                .addGap(3, 3, 3)
                                .addComponent(jL_FechaValor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jL_Contabilidad))
                            .addComponent(jP_Salida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_PrincipalLayout.createSequentialGroup()
                        .addGroup(jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL_NuevoProducto)
                            .addComponent(jL_Productos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCB_Productos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTF_NuevoProducto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jB_Crear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jB_Cargar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP_PrincipalLayout.setVerticalGroup(
            jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_PrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_NuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Crear)
                    .addComponent(jTF_NuevoProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Productos)
                    .addComponent(jCB_Productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Cargar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_PrincipalLayout.createSequentialGroup()
                        .addComponent(jP_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jL_Titulo))
                    .addGroup(jP_PrincipalLayout.createSequentialGroup()
                        .addComponent(jP_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jP_Salida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jL_Contabilidad1)
                        .addComponent(jL_FechaValor)
                        .addComponent(jL_Fecha))
                    .addComponent(jL_Contabilidad, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Cargar;
    private javax.swing.JButton jB_CargarFecha;
    private javax.swing.JButton jB_Crear;
    private javax.swing.JButton jB_Registrar;
    private javax.swing.JButton jB_Salida;
    private javax.swing.JComboBox<String> jCB_Fecha;
    private javax.swing.JComboBox<String> jCB_Productos;
    private javax.swing.JCheckBox jC_PrecioUR;
    private javax.swing.JLabel jL_Contabilidad;
    private javax.swing.JLabel jL_Contabilidad1;
    private javax.swing.JLabel jL_DisponibilidadS;
    private javax.swing.JLabel jL_Fecha;
    private javax.swing.JLabel jL_FechaActual;
    private javax.swing.JLabel jL_FechaValor;
    private javax.swing.JLabel jL_NuevoProducto;
    private javax.swing.JLabel jL_NuevoRegistro;
    private javax.swing.JLabel jL_Precio;
    private javax.swing.JLabel jL_PrecioUnitarioR;
    private javax.swing.JLabel jL_Productos;
    private javax.swing.JLabel jL_Resumen;
    private javax.swing.JLabel jL_Salida;
    private javax.swing.JLabel jL_Stock;
    private javax.swing.JLabel jL_Titulo;
    private javax.swing.JLabel jL_UnidadesR;
    private javax.swing.JLabel jL_UnidadesS;
    private javax.swing.JLabel jL_VentaMes;
    private javax.swing.JLabel jL_VentaTotal;
    private javax.swing.JPanel jP_Principal;
    private javax.swing.JPanel jP_Producto;
    private javax.swing.JPanel jP_Registro;
    private javax.swing.JPanel jP_Salida;
    private javax.swing.JTextField jTF_DisponibiliadS;
    private javax.swing.JTextField jTF_NuevoProducto;
    private javax.swing.JTextField jTF_Precio;
    private javax.swing.JTextField jTF_PrecioUR;
    private javax.swing.JTextField jTF_Stock;
    private javax.swing.JTextField jTF_UnidadesR;
    private javax.swing.JTextField jTF_UnidadesS;
    private javax.swing.JTextField jTF_VentaMes;
    private javax.swing.JTextField jTF_VentaTotal;
    // End of variables declaration//GEN-END:variables
}
